package npu.core

import chisel3._

// ============================================================================
// Metadata travelling together with one flat TPU output vector.
//
// Static control:
//   alu_mode
//   act_en
//   norm_mode
//   rope_en
//
// Dynamic in-band events:
//   param_update
//   fusion_change
//   norm_phase_change
//
// tile_start / tile_end identify the first/last row of one 16x16 output tile.
// ============================================================================
class VPUStreamMeta extends Bundle {
  // VPU1
  val alu_mode = UInt(2.W)

  val act_en = Bool()

  // VPU2
  val norm_mode = UInt(2.W)

  val rope_en = Bool()

  // Dynamic context events
  val param_update = Bool()

  val fusion_change = Bool()

  val norm_phase_change = Bool()

  // Output tile boundary
  val tile_start = Bool()

  val tile_end = Bool()
  
}


// ============================================================================
// Tile-level metadata generated by ComputeTimer.
//
// This is stored once per completed output tile and later attached to all
// sixteen de-skewed output rows.
// ============================================================================
class TileMeta extends Bundle {

  val alu_mode = UInt(2.W)

  val act_en = Bool()

  val norm_mode = UInt(2.W)

  val rope_en = Bool()

  val param_update = Bool()

  val fusion_change = Bool()

  val norm_phase_change = Bool()

}